SAP/terraform-exporter-btp

.lycheeignore
- Add links to be excluded from check runs
- closes #8 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Check infrastructure
```
- Additional test steps
```
Run link checker GH Action
```
- Links are validated successfully
n/a
=> chore: add links to exclude from check

pkg/tfimportprovider/tfImportProviderFactory.go
- Refcatoring to reduce cyclomatic dependencies of Import Provider Factory
- closes # 174
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```bash
make test
```
n/a
=> refactor: reduce cyclomatic finding of import provider factory

pkg/tfutils/tfConfig.go
- Mitigate finding from go report on cyclomatic dependencies for tfConfig.go
- closes #170
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```bash
make test
```
n/a
=> refactor: reduce cyclomatic finding tfconfig

.github/workflows/create-gh-page.yml, .github/workflows/release.yml
- Add gh-pages generation
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Pipelines
```
=> chore: Update release action

pkg/tfimportprovider/cloudFoundryRouteImportProvider.go, pkg/tfimportprovider/cloudFoundryRouteImportProvider_test.go, pkg/tfimportprovider/tfImportProviderFactory.go, pkg/tfutils/tfConfig.go, pkg/tfutils/tfDocs.go, pkg/tfutils/tfImport.go
- Added support for exporting cloudfoundry routes
- Closes #71 
```
[] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
make test
```
- Additional test steps
```
...
```
- ...
=> feat: added support for exporting cloudfoundry_routes

pkg/tfutils/tfConfig.go
- Prompt if a directory should be overwritten contains the name of the directory
- Closes #206
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
- Additional test steps
```
Abort an export and restart it
```
- You get several prompts that a directory will be overwritten stating which directory is in scope of the action
n/a
=> fix: show config directory to be deleted

.wordlist.txt, docs/prerequisites.md
- Add missing information about supported environment variables
- Closes #203
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
- The documentation contains information about the supported environment variables
n/a
=> docs: add information about supported environment variables

docs/limitations.md, docs/prerequisites.md, mkdocs.yml
- Add description of import limitations
- closes #192
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
- Limitations about importable and supported resources are outlined in documentation
n/a
=> docs: add import limitations

.reuse/dep5, README.md, cmd/createJson.go, cmd/exportByJson.go, mkdocs.yml
- Yearly update references of copyright/licenses
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: year update
```
```bash
make test
```
GH pages must be recreated when PR is merged
=> chore: update year references

pkg/tfutils/tfConfig.go
- Fix missing authentication validation for TLS scenarios
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> fix: missing auth validation

.github/workflows/codeql.yml, guidelines/DEVELOPER-GUIDE.md, pkg/tfutils/tfImport.go
- Update Terraform provider versions to latest (BTP: 1.9.0, CF: 1.2.0)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependency Update
```
```bash
make test
```
n/a
=> chore: update Terraform to latest

.github/ISSUE_TEMPLATE/bug_report.yml
- Update release information for template
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update of issue template
```
=> chore: prep release

.github/workflows/test.yml, README.md
- Fix download of coverage report for Sonar Cloud
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Test Setup
```
```bash
make test
```
n/a
=> fix: download of path to coverage report

.github/workflows/release.yml, .github/workflows/test.yml
- Set caching of GH Actiomn to setup go to false to avoid tar error `Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: GH Action setup
```
```bash
make test
```
n/a
=> chore: gh action go setup

.github/workflows/assign-project.yml
- GH Action to automatically assign issues and pull requests to the central project board
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: automation setup
```
```bash
make test
```
n/a
=> chore: assign issue/pr to central project

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/assign-issue-to-project.yml, .github/workflows/set-default-values-pr.yml
- Automate setting of default values for PR namely:
- Add to default project
- Assign autor to PR
- Set milestone to next open one
- Reduce PR template
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Project automation
```
```bash
make test
```
n/a
=> chore: pr default automation

.github/workflows/assign-issue-to-project.yml, .github/workflows/pre-release-check.yml, .github/workflows/release.yml
- Improve setup of release:
- Execute test and integration test as prerequisite for release
- Add pre-release check as new GH Action
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Release Setup
```
```bash
make test
```
n/a
=> chore: release automation setup

cmd/root.go
- Fix link to authentication information in `btpf --help`
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Execute `btptf --help` and verify link for authentication
n/a
=> docs: fix link to authentication information

integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json, integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
- Update reference data for integration test after enhancement of CF export
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Test Setup
```
```bash
make test
```
The secret `CFORG_EXPORT_BY_JSON_REF` must be updated with new reference data
=> chore: update reference data for integration test

pkg/tfimportprovider/cloudFoundrySpaceRoleImportProvider.go, pkg/tfutils/tfConfig_test.go, pkg/tfutils/tfImport.go
- update cf provider version
- code cleanup for cf spase role import block
- closes #269 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```bash
make test
```
=> chore: update cf provider version to 1.3.0

cmd/CreateJsonHelper.go, cmd/exportByJsonHelper.go, cmd/exportByResource.go, docs/tfcodeimprovements.md, pkg/tfcleanup/generic_tools/generic_tools.go, pkg/tfcleanup/generic_tools/generic_types.go, pkg/tfcleanup/orchestrator/orchestrator.go, pkg/tfcleanup/provider_processor/provider_processor.go, pkg/tfcleanup/provider_processor/provider_types.go, pkg/tfcleanup/resource_processor/btp_directory_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_trust_configuration_processor.go, pkg/tfcleanup/resource_processor/cloudfoundry_org_processor.go, pkg/tfcleanup/resource_processor/resource_processor.go, pkg/tfcleanup/resource_processor/types_btp_directory.go, pkg/tfcleanup/resource_processor/types_btp_entitlements.go, pkg/tfcleanup/resource_processor/types_btp_service_instance.go, pkg/tfcleanup/resource_processor/types_btp_subaccount.go, pkg/tfcleanup/resource_processor/types_btp_subscriptions.go, pkg/tfcleanup/resource_processor/types_cloudfoundry.go, pkg/tfcleanup/resource_processor/types_generic.go
- This PR contains the cleanup of the trust configuration namely:
- removal of default traust from resource configuration
- removal of corresponding import block
- update of summary table of exported resources
- It also contains a major rework of the cleanup code to improve reuse and readability
- Closes #272
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
n/a
=> feat: trust config cleanup

.goreleaser.yml
- Closes #286
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Upgrade goreleaser configuration
```
```bash
make test
```
- Check that `goreleaser check .goreleaser.yml` runs successfully
n/a
=> chore: fix goreleaser warning

README.md, go.mod
- Update to latest go version
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update Go version
```
```bash
make test
```
For detail of Go version 1.24 see: https://tip.golang.org/doc/go1.24
=> chore: upgrade to latest go version

internal/cfcli/client.go, pkg/tfcleanup/generic_tools/generic_tools.go, pkg/tfcleanup/generic_tools/generic_types.go, pkg/tfcleanup/resource_processor/cloudfoundry_space_processor.go, pkg/tfcleanup/resource_processor/resource_processor.go
- This PR improves the generated Terraform configuration by replacing the ID of the space with the reference to the space resource if existing
- closes #267 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```bash
make test
```
=> feat: code reusability - add space dependency for CF resources

docs/tfcodeimprovements.md, pkg/tfcleanup/orchestrator/orchestrator.go
- Make the code clean up feature default
- Closes #294 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
You can switch this feature **off** by setting the environment variable `BTPTF_PLAIN` to a non-empty value.
=> feat: make code cleanup default

docs/resume.md
- Fix layout of bullet points for resume run documentation
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Check that the bullet points are rendered as such in the <https://sap.github.io/terraform-exporter-btp/resume/>
n/a
=> docs: fix layout of resume doc

docs/resume.md
- Another run to get bullet points formatted correctly with mkdocs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
- Unorder list for resume run documentation is rendered correctly
n/a
=> docs: formatting

cmd/root.go, docs/btptf.md
- Add output of the version to the CLI root command
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
n/a
=> feat: version output

.github/ISSUE_TEMPLATE/bug_report.yml, README.md
- Update README on details about versions and productive usage
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: update version information

README.md
- Fix markdown issue with highlight
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
=> chore: fix markdown issue

cmd/exportByJson.go, cmd/exportByResource.go, docs/btptf.md, mkdocs.yml
- Refine commands
- Refine doc structure
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
=> chore: refinement of docs and command help

.github/workflows/validate_build_win.yml
- Validate that go code build on windows
- Safety net for not using packages that have limitations on Windows
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Build setup
```
```bash
make test
```
=> chore: validate source code builds on Windows

.github/workflows/integration-test.yml, guidelines/DEVELOPER-GUIDE.md, integration-test/sample-setup/configs.tm.hcl, integration-test/sample-setup/stacks/btp_dev/_terramate_generated_provider.tf, pkg/tfutils/tfImport.go
- Update Terraform provider version to 1.11.0
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Internal setup
```
```bash
make test
```
n/a
=> chore: update Terraform provider version

cmd/exportByJson.go, cmd/exportByResource.go, docs/btptf.md
- refinement inline help of CLI commands
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: inline app help

cmd/createJson.go, cmd/exportByJson.go, cmd/exportByResource.go, cmd/root.go, docs/btptf.md, pkg/files/fileIo.go, pkg/output/output.go
- The output message contains the name of the folder or file name that was used for the export or creation of JSON inventory
- The output message has a clickable link to the folder where the created artifacts are stored
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
n/a
=> feat: clickable output target

.github/ISSUE_TEMPLATE/bug_report.yml, README.md
- Update references to prepare release candidate 1.0.0rc1
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update of references
```
```bash
make test
```
n/a
=> chore: prep release candidate

cmd/createJson.go, cmd/exportByResource.go
- Align inline documentation with temporal limitations of CF provider
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
See #298
=> docs: align inline documentation with temporal limitations

cmd/cmdMarkdownHelper.go, docs/btptf.md
- Remove markdown comments
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: update docs

docs/concepts.md, docs/gettingstarted.md, docs/install.md
- fix formating issues in generated docs"
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: fix formating issues in generated docs

.github/workflows/update-brew-formula.yaml
- Initial file for creating bre-formula workflow
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release Workflow
```
=> chore: Create update-brew-formula.yaml

docs/gettingstarted.md, docs/index.md, pkg/output/output.go
- update support section
- NEXTSTEPS.md refinement
- Closes #332
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: update support section and refine NextSteps.md

.github/scripts/update-btptf-brew-formula.sh, .github/workflows/update-brew-formula.yaml, btptf.rb
- Brew build action: Will run against latest release
- update-brew-formula scrit creats the brew formula file
- Finally creates PR for the new generated formula
- To add/install run `brew tap SAP/terraform-exporter-btp https://github.com/SAP/terraform-exporter-btp`
-  Until its merged go to location where homebrew clones the repo (`/usr/local/Homebrew/Library/Taps/sap/homebrew-terraform-exporter-btp`) and checkout the `rel-check2` branch
-  Run `brew install sap/terraform-exporter-btp/btptf`
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Added Hoebrew build action
```
=> chore: Add Homebrew build action

.github/workflows/update-brew-formula.yaml
- Add write and PR permissions to the Workflow
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: GH action permission fix
```
=> chore: Add permissions

cmd/createJson.go, cmd/exportByResource.go, integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json, integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json, pkg/tfutils/tfConfig.go, pkg/tfutils/tfImport.go
- integration of new resource `cloudfoundry_user_cf`
- update import flow for Cloud Foundry users
- update integration tests for Cloud Foundry
- closes #298
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
See https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/user_cf
=> fix: import of Cloud Foundry users

pkg/tfutils/tfImport.go
- Refine code for filtering default values from JSON data
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Code improvement
```
```bash
make test
```
n/a
=> chore: refine code for JSON filtering

README.md
- Update README.md: remove beta and RC information
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: update README.md for GA

docs/prerequisites.md, pkg/tfutils/tfConfig.go, pkg/tfutils/tfConfig_test.go
- abort processing when SSO parameter is set
- closes #361
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> fix: issue when SSO Environment parameter ist set

pkg/tfutils/tfConfig_test.go, pkg/tfutils/tfImport.go
Update cf terraform provider used version to v1.5.0 
closes #367
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update CF Version
```
```bash
make test
```
=> chore: Update CF version

pkg/tfutils/tfImport.go
- Version upgrade of Terraform provider for SAP BTP to lates (v1.12.0)
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependency update
```
```bash
make test
```
See release notes: https://github.com/SAP/terraform-provider-btp/releases/tag/v1.12.0
=> chore: verion update of TF provider BTP

pkg/tfcleanup/resource_processor/resource_processor.go
- Snsure that for each combination of service name and plan name only one data source gets created even if multiple service instances refering to the same plan are part of the export
- closes #375
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> fix: creation of duplicate data sources

cmd/root.go
- Update version number to 1.1.0
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Release preparation
```
```bash
make test
```
n/a
=> chore: prep release 1.1.0

docs/gettingstarted.md
- Another typo in the code samples
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
=> docs: typo for code samples

.wordlist.txt, docs/prerequisites.md, docs/troubleshooting.md
- Enhancement of the prerequisites section for the installation of the Terraform/OpenTofu CLI to be available on the `PATH` environment variable.
- Enhancement of the troubleshooting section for the same purpose
- closes #384
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```bash
make test
```
n/a
=> docs: enhance prerequisites for Terraform/OpenTofu CLI

.github/workflows/publish-chocolatey-package.yml, choco/sap-btptf.nuspec, choco/tools/chocolateyInstall.ps1, choco/tools/chocolateyUninstall.ps1, choco/tools/uninstall.ps1
- Based on auto validations
- change release name to `sap-btptf`. `.` are no longer allowed
- change installs script names to convention
- added suggested fields in `nuspec`
- changes based on validations
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Package Creation 
```
```bash
make test
```
=> chore: Choco improvements

.github/workflows/publish-winget-package.yaml
- initial structure
- changes may be needed once merged
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: GH Action
```
```bash
make test
```
=> chore: Add winget action

.github/workflows/publish-chocolatey-package.yml
- Add path to the upload artifact.
- Useful for downloading and testing the package right after the release created, even if not pushed to chocolatey
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: GH Action
```
```bash
make test
```
=> chore: minor fix - choco-action

.wordlist.txt, docs/install.md, mkdocs.yml
- Additional section for package installation
- Addresses #48 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation
```
```bash
make test
```
=> chore: Add installer documentation

.github/scripts/compareJson.js, .github/scripts/package-lock.json, .github/scripts/package.json, .github/workflows/integration-test.yml, .gitignore
- Execute the integration tests sequentially switching between BTP and CF to avoid rate limiting issues.
- Change object comparisom to lodash for better performance and reliability.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: test setup
```
```bash
make test
```
=> chore: change integration test setup for more resillience

.github/workflows/release.yml
- Temporal removal of integration test from release process due to constant issues from the platform
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: internal test setup
```
```bash
make test
```
- Tests were executed locally and passed
- Follow up issue is open: #408
=> chore: integration test for release

.github/workflows/integration-test.yml, .github/workflows/release.yml, .github/workflows/update-brew-formula.yaml
- refactoring of integration test setup namely:
- Splitting every scenario in a dedicated job as this allows granular repeats of the jobs that errored out
- Cache dependencies of go and node setups to reduce waiting times and network traffic
- Introduce waiting times to relax the calling of the Backend APIs
- Introduce manual override for release process if steps fail
- Activation of integration test in release workflow
- closes #408 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
[X] Other... Please describe: Refactoring of test setup
```
```bash
make test
```
- Automated …
=> refactor: Integration test setup

.github/workflows/publish-winget-package.yaml
- Added variable FORK_OWNER
- For now work with personal repo
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: gh action fix
```
```bash
make test
```
=> chore: winget bug-fix

.wordlist.txt, Makefile, choco/tools/chocolateyInstall.ps1, docs/install.md
- Add choco installation into docs
- Final touchup to the choco install script
addresses #403 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Choco install
```
```bash
make test
```
=> chore: Add choco docs

.devcontainer/default/devcontainer.json, .devcontainer/withenvfile/devcontainer.json
- Update OpenTofu version in dev containers to latest
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: dev setup, dependency update
```
```bash
make test
```
If you are using dev containers you must rebuild the container to pick up the new OpenTofu version.
=> chore: update opentofu version in dev containers

docs/tfcodeimprovements.md, pkg/tfcleanup/generic_tools/generic_tools.go, pkg/tfcleanup/generic_tools/generic_tools_test.go, pkg/tfcleanup/generic_tools/generic_types.go, pkg/tfcleanup/orchestrator/orchestrator.go, pkg/tfcleanup/provider_processor/provider_process_test.go, pkg/tfcleanup/resource_processor/btp_role_processor_test.go, pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor_test.go, pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor_test.go, pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go, pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor_test.go, pkg/tfcleanup/resource_processor/resource_processor.go, pkg/toggles/toggles.go
- add entitlements module to generated code:
- Replace single entitlements by module
- Add variable to fill module parameter for entitlement based on single entitlements
- Adjust dependency handling for subscriptions and service instance
- Replace generated import blocks by import blocks pointing to module addresses 
- Introduce feature flag for activation of feature
- adjust test cases
- fix service plan dependency if subaccount is not exported
- Enhance docs with info about beta features
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```bash
make test
```
Verify that the …
=> feat: adjust code to use entitlements module

pkg/tfutils/tfConfig_test.go, pkg/tfutils/tfImport.go
- Update provider versions to latest
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependency Update
```
```bash
make test
```
=> chore: update provider versions

cmd/root.go
- New release of the Terraform Exporter for SAP BTP
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: pre-work release
```
```bash
make test
```
=> chore: new release

cmd/root.go, pkg/tfutils/tfImport.go
- Upate Terraform provider version (hotfix)
- Update btp exporter version to 1.3.1
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
```bash
make test
```
n/a
=> chore: version update

README.md, go.mod
- Update Go version to version 1.25
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update of Go version to latest
```
```bash
make test
```
Release Notes: https://go.dev/doc/go1.25
=> chore: update go version to 1.25

.devcontainer/default/devcontainer.json, .devcontainer/withenvfile/devcontainer.json
- Update dev container configurations
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Internal setup
```
```bash
make test
```
n/a
=> chore: update dev container configurations

.github/ISSUE_TEMPLATE/bug_report.yml, cmd/root.go
- prepare release 1.4.0 of the exporter
- mainly dependency updates
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: prep release
```
```bash
make test
```
n/a
=> chore: prepare release 1.4.0
